---
#Import installation tasks from a file
- name: main.yml | Import extra tasks
  ansible.builtin.import_tasks:
    file: install.yml

# Import extra tasks from a file
- name: main.yml | Import extra tasks
  ansible.builtin.import_tasks:
    file: extra.yml

# Build the report File - DEB
- name: main.yml | Build the report File
  ansible.builtin.template:
    src: "csvtemplate_deb.j2"
    dest: "{{ tmp_path_file }}"
  when: ansible_facts['os_family'] == 'Debian'

# Build the report File - RPM
- name: main.yml | Build the report File
  ansible.builtin.template:
    src: "csvtemplate_rpm.j2"
    dest: "{{ tmp_path_file }}"
  when: ansible_facts['os_family'] == 'RedHat'

# Fetch the report file
- name: main.yml | Fetch the report file
  ansible.builtin.fetch:
    src: "{{ tmp_path_file }}"
    dest: "{{ output_path }}{{ inventory_hostname }}_{{ ansible_facts['date_time']['year'] }}-{{ ansible_facts['date_time']['month'] }}-{{ ansible_facts['date_time']['day'] }}_{{ ansible_facts['date_time']['hour'] }}-{{ ansible_facts['date_time']['minute'] }}-{{ ansible_facts['date_time']['second'] }}_{{ dmidecode_var.stdout | regex_replace('\\s+', '') }}_INF.txt"
    flat: yes

# Remove the report from TMP folder
- name: main.yml | Clean up report file
  ansible.builtin.file:
    path: "{{ tmp_path_file }}"
    state: absent