---
- name: Remove users and attempts to remove directories associated with the them
  hosts: all
  gather_facts: true
  vars_files:
    - creds.yml
  tasks:
    - name: Remove users
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        force: true
        state: absent
        remove: yes
      loop: "{{ remusers }}"

    - name: Remove files referencing users from sudoers
      ansible.builtin.file:
        path: "/etc/sudoers.d/{{ item['name'] }}"
        state: absent
      loop: "{{ remusers }}"
