---
# tasks file for remove_user
- name: Check if the user {{ user_to_remove_name }} is defined
  ansible.builtin.fail:
    msg: "The 'user_to_remove_name' variable must be defined. Please specify the user to remove."
  when: user_to_remove_name is not defined or user_to_remove_name | length == 0

- name: Ensure {{ user_to_remove_name }} is removed
  ansible.builtin.user:
    name: "{{ user_to_remove_name }}"
    state: absent
    remove: "{{ user_to_remove_home }}"
