---
- name: Setup a DNS nameserver(s) for clients
  hosts: all
  vars:
    -
  tasks:
    # Prerequisites
    - name: Check if NetworkManager is running
      ansible.builtin.service:
        name: NetworkManager
        status: started
        enabled: true
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Check if systemd-networkd is running
      ansible.builtin.service:
        name: systemd-networkd
        status: started
        enabled: true
      when: ansible_facts['os_family'] == 'Debian'
        
    # Setup a DNS domain/nameservers
    #- name: Setup DNS records on RHEL systems
    #  ansible.builtin.template:
    #    src: nameservers-template.j2
    #    dest: /etc/resolv.conf
    #
    #- name: 
