---
# defaults file for openscap_report

debPolicyName: ""
rpmPolicyName: ""
debProfileID: ""
rpmProfileID: ""

tmpDest: /tmp/
tmpResultsFile: /tmp/openscap_result.xml
tmpReportFile: /tmp/openscap_report.html
