#
# First run execute with parameters: --ask-pass --ask-become-pass
---
- name: User privileges and ssh keys setup
  hosts: all
  vars:
    username: mb
  tasks: 
  - name: Creates a record in sudoers.d folder, give the user {{ username }} ability to execute without password
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/mb
      create: true
      mode: '0440'
      owner: root
      group: root
      line: 'mb ALL=(ALL:ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
  
  - name: Set authorized key for the user {{ username }}
    ansible.posix.authorized_key:
      user: "{{ username }}"
      key: "{{ lookup('ansible.builtin.file', '../secrets/anskey.pub') }}"
      state: present
