---
all:
  vars:
    ansible_user: mb
    ansible_become: true
    ansible_ssh_port: 22
    ansible_ssh_private_key_file: secrets/anskey
    # ansible_host_key_checking: false            # testing

  children:
    docker:
      hosts:
        lab-docker:
          ansible_host: 172.16.0.10
    kube:
      hosts:
        lab-kube-master-01:
          ansible_host: 172.16.0.20
        lab-kube-worker-01:
          ansible_host: 172.16.0.21
        lab-kube-worker-02:
          ansible_host: 172.16.0.22
